server:
  port: 8080

spring:
  application:
    name: VLIASCRM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vliascrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: qichengxu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

logging:
  level:
    com.example.vliascrm: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  packagesToScan: com.example.vliascrm.controller
  pathsToMatch: /api/**

# 自定义配置
app:
  jwt:
    secret: VLIASCRMJWTSecretKey2024ForEnterpriseLevelSystemVerySecureAndLongEnoughFor256BitsRequirementRandomString1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
    expiration: 604800 # 7天，单位秒
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  file:
    upload-dir: uploads 

# 权限同步配置
vlias:
  permission-sync:
    enabled: true  # 启用权限同步功能
    modules:
      # 系统管理模块
      - name: "系统管理"
        code: "system"
        description: "系统管理功能"
        sort: 1
        submodules:
          - name: "用户管理"
            code: "user-management"
            description: "用户管理功能"
            sort: 1
            operations:
              - name: "查看用户"
                code: "view"
                description: "查看用户列表"
                sort: 1
              - name: "新增用户"
                code: "create"
                description: "新增用户"
                sort: 2
              - name: "编辑用户"
                code: "edit"
                description: "编辑用户信息"
                sort: 3
              - name: "删除用户"
                code: "delete"
                description: "删除用户"
                sort: 4
          
          - name: "角色管理"
            code: "role-management"
            description: "角色管理功能"
            sort: 2
            operations:
              - name: "查看角色"
                code: "view"
                description: "查看角色列表"
                sort: 1
              - name: "新增角色"
                code: "create"
                description: "新增角色"
                sort: 2
              - name: "编辑角色"
                code: "edit"
                description: "编辑角色信息"
                sort: 3
              - name: "删除角色"
                code: "delete"
                description: "删除角色"
                sort: 4
          
          - name: "权限管理"
            code: "permission-management"
            description: "权限管理功能"
            sort: 3
            operations:
              - name: "查看权限"
                code: "view"
                description: "查看权限列表"
                sort: 1
              - name: "新增权限"
                code: "create"
                description: "新增权限"
                sort: 2
              - name: "编辑权限"
                code: "edit"
                description: "编辑权限信息"
                sort: 3
              - name: "删除权限"
                code: "delete"
                description: "删除权限"
                sort: 4
          
          - name: "菜单管理"
            code: "menu-management"
            description: "菜单管理功能"
            sort: 4
            operations:
              - name: "查看菜单"
                code: "view"
                description: "查看菜单列表"
                sort: 1
              - name: "新增菜单"
                code: "create"
                description: "新增菜单"
                sort: 2
              - name: "编辑菜单"
                code: "edit"
                description: "编辑菜单信息"
                sort: 3
              - name: "删除菜单"
                code: "delete"
                description: "删除菜单"
                sort: 4
          
          - name: "字典管理"
            code: "dict-management"
            description: "数据字典管理功能"
            sort: 5
            operations:
              - name: "查看字典"
                code: "view"
                description: "查看字典列表"
                sort: 1
              - name: "新增字典"
                code: "create"
                description: "新增字典"
                sort: 2
              - name: "编辑字典"
                code: "edit"
                description: "编辑字典信息"
                sort: 3
              - name: "删除字典"
                code: "delete"
                description: "删除字典"
                sort: 4

      # 组织架构模块
      - name: "组织架构"
        code: "org"
        description: "组织架构管理功能"
        sort: 2
        submodules:
          - name: "组织机构管理"
            code: "org-management"
            description: "组织机构管理功能"
            sort: 1
            operations:
              - name: "查看组织"
                code: "view"
                description: "查看组织列表"
                sort: 1
              - name: "新增组织"
                code: "create"
                description: "新增组织"
                sort: 2
              - name: "编辑组织"
                code: "edit"
                description: "编辑组织信息"
                sort: 3
              - name: "删除组织"
                code: "delete"
                description: "删除组织"
                sort: 4
          
          - name: "部门管理"
            code: "dept-management"
            description: "部门管理功能"
            sort: 2
            operations:
              - name: "查看部门"
                code: "view"
                description: "查看部门列表"
                sort: 1
              - name: "新增部门"
                code: "create"
                description: "新增部门"
                sort: 2
              - name: "编辑部门"
                code: "edit"
                description: "编辑部门信息"
                sort: 3
              - name: "删除部门"
                code: "delete"
                description: "删除部门"
                sort: 4
          
          - name: "岗位管理"
            code: "position-management"
            description: "岗位管理功能"
            sort: 3
            operations:
              - name: "查看岗位"
                code: "view"
                description: "查看岗位列表"
                sort: 1
              - name: "新增岗位"
                code: "create"
                description: "新增岗位"
                sort: 2
              - name: "编辑岗位"
                code: "edit"
                description: "编辑岗位信息"
                sort: 3
              - name: "删除岗位"
                code: "delete"
                description: "删除岗位"
                sort: 4

      # 商品管理模块
      - name: "商品管理"
        code: "product"
        description: "商品管理功能"
        sort: 3
        submodules:
          - name: "商品信息管理"
            code: "product-info-management"
            description: "商品信息管理功能"
            sort: 1
            operations:
              - name: "查看商品"
                code: "view"
                description: "查看商品列表"
                sort: 1
              - name: "新增商品"
                code: "create"
                description: "新增商品"
                sort: 2
              - name: "编辑商品"
                code: "edit"
                description: "编辑商品信息"
                sort: 3
              - name: "删除商品"
                code: "delete"
                description: "删除商品"
                sort: 4
          
          - name: "商品分类管理"
            code: "product-category-management"
            description: "商品分类管理功能"
            sort: 2
            operations:
              - name: "查看分类"
                code: "view"
                description: "查看分类列表"
                sort: 1
              - name: "新增分类"
                code: "create"
                description: "新增分类"
                sort: 2
              - name: "编辑分类"
                code: "edit"
                description: "编辑分类信息"
                sort: 3
              - name: "删除分类"
                code: "delete"
                description: "删除分类"
                sort: 4
          
          - name: "商品品牌管理"
            code: "product-brand-management"
            description: "商品品牌管理功能"
            sort: 3
            operations:
              - name: "查看品牌"
                code: "view"
                description: "查看品牌列表"
                sort: 1
              - name: "新增品牌"
                code: "create"
                description: "新增品牌"
                sort: 2
              - name: "编辑品牌"
                code: "edit"
                description: "编辑品牌信息"
                sort: 3
              - name: "删除品牌"
                code: "delete"
                description: "删除品牌"
                sort: 4
          
          - name: "商品规格管理"
            code: "product-specification-management"
            description: "商品规格管理功能"
            sort: 4
            operations:
              - name: "查看规格"
                code: "view"
                description: "查看规格列表"
                sort: 1
              - name: "新增规格"
                code: "create"
                description: "新增规格"
                sort: 2
              - name: "编辑规格"
                code: "edit"
                description: "编辑规格信息"
                sort: 3
              - name: "删除规格"
                code: "delete"
                description: "删除规格"
                sort: 4
          
          - name: "商品属性管理"
            code: "product-attribute-management"
            description: "商品属性管理功能"
            sort: 5
            operations:
              - name: "查看属性"
                code: "view"
                description: "查看属性列表"
                sort: 1
              - name: "新增属性"
                code: "create"
                description: "新增属性"
                sort: 2
              - name: "编辑属性"
                code: "edit"
                description: "编辑属性信息"
                sort: 3
              - name: "删除属性"
                code: "delete"
                description: "删除属性"
                sort: 4
          
          - name: "SKU管理"
            code: "product-sku-management"
            description: "SKU管理功能"
            sort: 6
            operations:
              - name: "查看SKU"
                code: "view"
                description: "查看SKU列表"
                sort: 1
              - name: "新增SKU"
                code: "create"
                description: "新增SKU"
                sort: 2
              - name: "编辑SKU"
                code: "edit"
                description: "编辑SKU信息"
                sort: 3
              - name: "删除SKU"
                code: "delete"
                description: "删除SKU"
                sort: 4

      # 个人中心模块
      - name: "个人中心"
        code: "profile"
        description: "个人信息管理功能"
        sort: 999
        submodules:
          - name: "个人信息管理"
            code: "profile-info-management"
            description: "个人信息管理功能"
            sort: 1
            operations:
              - name: "查看信息"
                code: "view"
                description: "查看个人信息"
                sort: 1
              - name: "编辑信息"
                code: "edit"
                description: "编辑个人信息"
                sort: 2
              - name: "修改密码"
                code: "password"
                description: "修改个人密码"
                sort: 3 

 