server:
  port: 8080

spring:
  application:
    name: VLIASCRM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vliascrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: qichengxu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

logging:
  level:
    com.example.vliascrm: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  packagesToScan: com.example.vliascrm.controller
  pathsToMatch: /api/**

# 自定义配置
app:
  jwt:
    secret: VLIASCRMJWTSecretKey2024ForEnterpriseLevelSystemVerySecureAndLongEnoughFor256BitsRequirement1234567890
    expiration: 604800 # 7天，单位秒
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  file:
    upload-dir: uploads 

# 权限同步配置
vlias:
  permission-sync:
    enabled: true  # 启用权限同步功能
    modules:
      # 系统管理模块
      - name: "系统管理"
        code: "sys"
        description: "系统基础功能管理"
        sort: 1
        operations:
          - name: "用户管理"
            code: "user"
            description: "用户增删改查操作"
            sort: 1
          - name: "角色管理"
            code: "role"
            description: "角色增删改查操作"
            sort: 2
          - name: "权限管理"
            code: "permission"
            description: "权限增删改查操作"
            sort: 3
          - name: "菜单管理"
            code: "menu"
            description: "菜单增删改查操作"
            sort: 4
          - name: "字典管理"
            code: "dict"
            description: "数据字典管理操作"
            sort: 5

      # 组织架构模块
      - name: "组织架构"
        code: "org"
        description: "组织架构管理"
        sort: 2
        operations:
          - name: "组织管理"
            code: "organization"
            description: "组织机构增删改查操作"
            sort: 1
          - name: "部门管理"
            code: "department"
            description: "部门增删改查操作"
            sort: 2
          - name: "岗位管理"
            code: "position"
            description: "岗位增删改查操作"
            sort: 3

      # 商品管理模块
      - name: "商品管理"
        code: "product"
        description: "商品信息管理"
        sort: 3
        operations:
          - name: "商品管理"
            code: "goods"
            description: "商品增删改查操作"
            sort: 1
          - name: "分类管理"
            code: "category"
            description: "商品分类管理操作"
            sort: 2
          - name: "品牌管理"
            code: "brand"
            description: "商品品牌管理操作"
            sort: 3 

 