server:
  port: 8080

spring:
  application:
    name: VLIASCRM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vliascrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: qichengxu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

logging:
  level:
    com.example.vliascrm: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  packagesToScan: com.example.vliascrm.controller
  pathsToMatch: /api/**

# 自定义配置
app:
  jwt:
    secret: g8shUE86YrSytAXbfOkqbI8y2vrdPhT9k6M5fwJN20aCDxVlLpZz7HcGe3RiWjK4dW4cD7vG9sBn3MqP5zLxK1jQtR8fE6yH0uI2oA3pS4vF8dT7hG9jK2lZ5xC4vB3nM
    expiration: 604800 # 7天，单位秒
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  file:
    upload-dir: uploads 