server:
  port: 8080

spring:
  application:
    name: VLIASCRM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vliascrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: qichengxu123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10s

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.example.vliascrm: info
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql: warn

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  packagesToScan: com.example.vliascrm.controller
  pathsToMatch: /api/**

# 自定义配置
app:
  jwt:
    secret: VLIASCRMJWTSecretKey2024ForEnterpriseLevelSystemVerySecureAndLongEnoughFor256BitsRequirementRandomString1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
    expiration: 604800 # 7天，单位秒
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  file:
    upload-dir: uploads
    base-url: # 文件访问基础URL，生产环境应设置为实际域名

  