spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 临时使用，会删除并重新创建所有表
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.example.vliascrm: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace 